title: Personal Notes
description: A collection of my personal learning notes and resources.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Justine Cho: https://juzcho.github.io/
